import streamlit as st

st.title("Octet '23 Spring Break")
st.image("main-image.jpg")
# have a selector of option 1, 2, 3
option = st.selectbox( "What location would you like to see?", ("Cancun", "San Juan", "Rio"))
if option == "Cancun":
    st.header("Cancun, Mexico")
    st.caption("Pitch by Kendrick Lamar:")
    st.audio("kendrick.wav")
    st.write("Cancun, the land of dreams, where the sand meets the sea The octet, we're gonna make it our own personal utopia Leaving behind the daily grind, like a bird breaking from its cage We'll let loose and fly, like a flock of wild geese on a rage Gobtet, we're coming for you, Cancun We'll soak up the sun and the moon, just like a sponge We'll drink in the culture and the sights, like a thirsty man in a desert We're gonna make this Spring Break one to remember, like a tattoo on a person's shirt")

    st.subheader("Example Itinerary")
    st.subheader("Day 1:")
    st.write("Free activity: Visit the Cancun Sign")
    st.write("Paid activity: Take a boat tour to Isla Mujeres")
    st.write("Breakfast: Huevos rancheros, a traditional Mexican dish, at a local restaurant")
    st.write("Lunch: Tacos al pastor, a traditional Mexican dish, at a local restaurant")
    st.write("Dinner: Cochinita pibil, a traditional Yucatecan dish, at a local restaurant")

    st.subheader("Day 2:")
    st.write("Free activity: Walk around the Hotel Zone")
    st.write("Paid activity: Visit the Mayan Museum of Cancun")
    st.write("Breakfast: Chilaquiles, a traditional Mexican dish, at a local restaurant")
    st.write("Lunch: Ceviche, a traditional Mexican seafood dish, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 3:")
    st.write("Free activity: Visit the Cancun Interactive Aquarium")
    st.write("Paid activity: Take a snorkeling or diving tour to the Mesoamerican Barrier Reef")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Tamales, a traditional Mexican dish, from a street vendor")
    st.write("Dinner: Paella, a traditional Spanish dish, at a local restaurant")

    st.subheader("Day 4:")
    st.write("Free activity: Visit the El Rey archaeological site")
    st.write("Paid activity: Visit the Cancun Underwater Museum")
    st.write("Breakfast: Huevos rancheros, a traditional Mexican dish, at a local restaurant")
    st.write("Lunch: Ceviche, a traditional Mexican seafood dish, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 5:")
    st.write("Free activity: Visit the Playa Delfines")
    st.write("Paid activity: Take a day trip to the Tulum ruins")
    st.write("Breakfast: Chilaquiles, a traditional Mexican dish, at a local restaurant")
    st.write("Lunch: Tamales, a traditional Mexican dish, from a street vendor")
    st.write("Dinner: Paella, a traditional Spanish dish, at a local restaurant")

    st.subheader("Day 6:")
    st.write("Free activity: Visit the Market 28")
    st.write("Paid activity: Take a spa day at a local resort")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Cochinita pibil, a traditional Yucatecan dish, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.header("Housing:")
    # st.image("airbnb4.png")
    st.subheader("Title: BALLIN near Beach")
    st.write("Price: $280 per person")
    st.write("Rating: 4.22/5")
    st.write("Link: https://www.airbnb.com/rooms/11345297?adults=5&check_in=2023-03-13&check_out=2023-03-21&source_impression_id=p3_1674450558_IG6QvpAVYbZEJXl1")

    # st.image("airbnb5.png")
    st.subheader("Title: In the city")
    st.write("Price: $134 per person")
    st.write("Rating: 4.52/5")
    st.write("Link: https://www.airbnb.com/rooms/48782880?adults=5&location=Cancun%2C%20Mexico&check_in=2023-03-13&check_out=2023-03-21&federated_search_id=867477bb-2488-4588-8fe1-595e8e8a90ed&source_impression_id=p3_1674450688_RONP%2BpLBnjW9t%2BnU")

    # st.image("airbnb6.png")
    st.subheader("Title: Budget (we maybe get sold into human trafficking)")
    st.write("Price: $98 per person")
    st.write("Rating: 4.74/5")
    st.write("Link: https://www.airbnb.com/rooms/15531322?adults=5&check_in=2023-03-13&check_out=2023-03-21&source_impression_id=p3_1674450639_ZCTYWg6XW50b2SCy")

    st.header("Flight Info")
    st.image("plane.jpg")
    st.subheader("Most expensive part by far")
    # st.image("cancunplane.PNG")
    st.write("457 per person for round trip")

    st.header("Total Cost:")
    st.write("Activites and Food: 250$")
    st.write("Housing: 98-280$")
    st.write("Flights: 457$")
    st.write("Total: 805-987$")
elif option == "San Juan":
    st.header("San Juan, Puerto Rico")
    st.caption("Pitch by Jermaine Cole:")
    st.audio("cole.wav")
    st.write("Island's got everything, got me feeling like a boss From the culture to the nightlife, it's lit like a fucking torch But it's not just about the party, this place got depth Got me feeling like a scholar, got me feeling like a fucking chief The beach is so fly, got me feeling like a king El Morro fortress, it's got me feeling like a lord Salsa dancing, got me in a trance San Juan, it's got me in a romance The island's got me feeling like a don")


    st.subheader("Example Itinerary")
    st.subheader("Day 1:")
    st.write("Free activity: Visit El Morro fortress")
    st.write("Paid activity: Take a boat tour to Palomino Island")
    st.write("Breakfast: Mofongo, a traditional Puerto Rican dish made with mashed plantains, at a local restaurant")
    st.write("Lunch: Pernil, slow-roasted pork shoulder, at a local restaurant")
    st.write("Dinner: Seafood at a local restaurant")

    st.subheader("Day 2:")
    st.write("Free activity: Walk around Old San Juan")
    st.write("Paid activity: Visit the San Juan National Historic Site")
    st.write("Breakfast: Tostones, twice-fried plantain slices, at a local restaurant")
    st.write("Lunch: Asopao, a traditional Puerto Rican stew, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 3:")
    st.write("Free activity: Visit the Paseo de la Princesa")
    st.write("Paid activity: Take a snorkeling or diving tour to the Bioluminescent Bay")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Empanadas, a traditional Puerto Rican fried pastry, from a street vendor")
    st.write("Dinner: Paella, a traditional Spanish dish, at a local restaurant")

    st.subheader("Day 4:")
    st.write("Free activity: Visit the San Cristobal fortress")
    st.write("Paid activity: Visit the Museum of Art of Puerto Rico")
    st.write("Breakfast: Mofongo, a traditional Puerto Rican dish made with mashed plantains, at a local restaurant")
    st.write("Lunch: Asopao, a traditional Puerto Rican stew, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 5:")
    st.write("Free activity: Visit the Condado beach")
    st.write("Paid activity: Take a bio bay kayak tour")
    st.write("Breakfast: Tostones, twice-fried plantain slices, at a local restaurant")
    st.write("Lunch: Empanadas, a traditional Puerto Rican fried pastry, from a street vendor")
    st.write("Dinner: Paella, a traditional Spanish dish, at a local restaurant")

    st.subheader("Day 6:")
    st.write("Free activity: Visit the Casa Bacardi")
    st.write("Paid activity: Visit the El Yunque National Forest")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Pernil, slow-roasted pork shoulder, at a local restaurant")
    st.write("Dinner: Seafood at a local restaurant")

    st.header("Housing:")
    # st.image("airbnb1.png")
    st.subheader("Title: Near Beach")
    st.write("Price: $194 per person")
    st.write("Rating: 4.33/5")
    st.write("Link: https://www.airbnb.com/rooms/45533377?adults=5&location=San%20Juan%2C%20Puerto%20Rico&check_in=2023-03-11&check_out=2023-03-17&federated_search_id=798ed4eb-8a6f-4970-b371-27ac8ccea284&source_impression_id=p3_1674449657_MFuvrDegEEJzkLuC")

    # st.image("airbnb2.png")
    st.subheader("Title: In the city")
    st.write("Price: $170 per person")
    st.write("Rating: 4.53/5")
    st.write("Link: https://www.airbnb.com/rooms/25843228?adults=5&location=San%20Juan%2C%20Puerto%20Rico&check_in=2023-03-11&check_out=2023-03-17&federated_search_id=4ead6313-c708-4285-b55c-658ecaf47b42&source_impression_id=p3_1674449792_%2FfvFC989WsRCcgBK")

    # st.image("airbnb3.png")
    st.subheader("Title: Budget (we maybe get sold into human trafficking)")
    st.write("Price: $115 per person")
    st.write("Rating: 4.48/5")
    st.write("Link: https://www.airbnb.com/rooms/52916686?adults=5&check_in=2023-03-11&check_out=2023-03-17&source_impression_id=p3_1674449905_LsnA7GlpW7TLfoAI")

    st.header("Flight Info")
    st.image("plane.jpg")
    st.subheader("Most expensive part by far")
    # st.image("sanjuanflight.PNG")
    st.write("379 per person for round trip")

    st.header("Total Cost:")
    st.write("Activites and Food: 250$")
    st.write("Housing: 115-194$")
    st.write("Flights: 379$")
    st.write("Total: 744-823$")
elif option == "Rio":
    st.header("Rio, Brazil")
    st.caption("A message from Batman:")
    st.audio("wayne.wav")
    st.write("Greetings citizens, Rio de Janeiro, Brazil, is the ultimate destination for your spring break. A place where pleasure and danger go hand in hand. From the Copacabana to the Christ the Redeemer, Rio will test your limits and push you to your brink. But remember, With great power comes great responsibility. Do not underestimate the city, or you will face the consequences. I'll be watching, The Batman.")

    st.subheader("Example Itinerary")
    st.subheader("Day 1:")
    st.write("Free activity: Visit Christ the Redeemer statue")
    st.write("Paid activity: Take a cable car ride to Sugarloaf Mountain")
    st.write("Breakfast: Acai bowl from a local street vendor")
    st.write("Lunch: Feijoada, a traditional Brazilian black bean stew, at a local restaurant")
    st.write("Dinner: Churrascaria, an all-you-can-eat Brazilian barbecue restaurant")

    st.subheader("Day 2:")
    st.write("Free activity: Walk around Lapa Arches")
    st.write("Paid activity: Visit the Museum of Tomorrow")
    st.write("Breakfast: Pao de queijo, traditional Brazilian cheese bread, from a bakery")
    st.write("Lunch: Moqueca, a traditional Brazilian fish stew, at a seafood restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 3:")
    st.write("Free activity: Visit the Botanical Garden")
    st.write("Paid activity: Take a samba class")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Pastel, a fried pastry filled with various fillings, from a street vendor")
    st.write("Dinner: Feijoada, a traditional Brazilian black bean stew, at a local restaurant")

    st.subheader("Day 4:")
    st.write("Free activity: Visit the Selaron Steps")
    st.write("Paid activity: Visit the Museum of Image and Sound")
    st.write("Breakfast: Acai bowl from a local street vendor")
    st.write("Lunch: Moqueca, a traditional Brazilian fish stew, at a seafood restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.subheader("Day 5:")
    st.write("Free activity: Visit the Copacabana beach")
    st.write("Paid activity: Take a favela tour")
    st.write("Breakfast: Pao de queijo, traditional Brazilian cheese bread, from a bakery")
    st.write("Lunch: Pastel, a fried pastry filled with various fillings, from a street vendor")
    st.write("Dinner: Churrascaria, an all-you-can-eat Brazilian barbecue restaurant")

    st.subheader("Day 6:")
    st.write("Free activity: Visit the Tijuca Forest National Park")
    st.write("Paid activity: Visit the National Museum of Brazil")
    st.write("Breakfast: Fresh fruit and yogurt at a local cafe")
    st.write("Lunch: Feijoada, a traditional Brazilian black bean stew, at a local restaurant")
    st.write("Dinner: Street food from a food truck or market")

    st.header("Housing:")
    # st.image("airbnb7.png")
    st.subheader("Title: Beach Front Copacabana Condo")
    st.write("Price: $189 per person")
    st.write("Rating: 4.84/5")
    st.write("Link: https://www.airbnb.com/rooms/20873953?adults=5&check_in=2023-03-11&check_out=2023-03-17&source_impression_id=p3_1674447056_YSTEs%2BbNWt%2FSlSfN")

    # st.image("airbnb8.png")
    st.subheader("Title: Funky Studio")
    st.write("Price: $92 per person")
    st.write("Rating: 4.89/5")
    st.write("Link: https://www.airbnb.com/rooms/47779389?adults=5&check_in=2023-03-11&check_out=2023-03-17&source_impression_id=p3_1674447379_KbhBz5oz%2Fsz0KPM8")

    # st.image("airbnb9.png")
    st.subheader("Title: Budget (we maybe get sold into human trafficking)")
    st.write("Price: $32 per person")
    st.write("Rating: 4.81/5")
    st.write("Link: https://www.airbnb.com/rooms/44461166?adults=5&location=Rio%20de%20Janeiro%2C%20Brazil&check_in=2023-03-11&check_out=2023-03-17&federated_search_id=074fd84c-6938-407f-b669-37f3269c067b&source_impression_id=p3_1674447560_0xgIuW6us1s3YE2G")

    st.header("Flight Info")
    st.image("plane.jpg")
    st.subheader("Most expensive part by far")
    st.write("839 per person for round trip")

    st.header("Total Cost:")
    st.write("Activites and Food: $250")
    st.write("Housing: $32-189")
    st.write("Flights: $839")
    st.write("Total: $1,121-1,278")



    
